version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - gocyclo
    - misspell
    - revive
    - sqlclosecheck
  disable:
    - gocritic
    - wsl
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
        - name: errorf
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocyclo
        path: _test\.go
      - linters:
          - revive
        text: should have comment
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
